#!/usr/bin/env python3
"""Render extension/assets/loader.gif – a spinner badge used as the default loading graphic."""
import math
from pathlib import Path
from PIL import Image, ImageDraw

SIZE, SS, FRAMES = 256, 4, 24
out = Path(__file__).resolve().parent.parent / 'extension' / 'assets' / 'loader.gif'

frames = []
for i in range(FRAMES):
    big = SIZE * SS
    img = Image.new('RGBA', (big, big), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    pad = 8 * SS
    d.ellipse([pad, pad, big - pad, big - pad], fill=(20, 18, 33, 255))
    r_pad = 62 * SS
    box = [r_pad, r_pad, big - r_pad, big - r_pad]
    width = 16 * SS
    d.arc(box, 0, 360, fill=(70, 66, 92, 255), width=width)          # track
    start = i * 360 / FRAMES
    d.arc(box, start, start + 100, fill=(255, 255, 255, 255), width=width)  # moving arc
    img = img.resize((SIZE, SIZE), Image.LANCZOS)
    # GIF has 1-bit alpha: solid where mostly opaque, transparent otherwise.
    alpha = img.getchannel('A').point(lambda a: 255 if a >= 128 else 0)
    rgb = Image.new('RGB', img.size, (20, 18, 33))
    rgb.paste(img.convert('RGB'), mask=alpha)
    p = rgb.quantize(colors=63, method=Image.Quantize.MEDIANCUT)
    p.putpalette(p.getpalette()[:63 * 3] + [255, 0, 255])
    p.paste(63, mask=alpha.point(lambda a: 255 - a))
    frames.append(p)

frames[0].save(out, save_all=True, append_images=frames[1:], duration=1000 // FRAMES * 2,
               loop=0, transparency=63, disposal=2, optimize=False)
print(out, out.stat().st_size, 'bytes')

# Also embed it as a JS module so the content script never has to fetch an
# extension URL (page CSP) – the blob is built from base64 at runtime.
import base64
js = out.parent.parent / 'lib' / 'loader-data.js'
js.write_text(
    '// Generated by tools/make-loader.py – default loading graphic (animated GIF).\n'
    f"export const LOADER_GIF_BASE64 = '{base64.b64encode(out.read_bytes()).decode()}';\n"
)
print(js, js.stat().st_size, 'bytes')
